#!/usr/bin/env python3
"""Build the marketplace plugin variant that relies on an external MCP gateway."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "plugins" / "rarcane"
DEFAULT_OUTPUT = ROOT / "dist" / "marketplace-no-mcp" / "rarcane"
MARKER = ".no-mcp-marketplace-artifact"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"artifact directory (default: {DEFAULT_OUTPUT.relative_to(ROOT)})",
    )
    return parser.parse_args()


def resolve_output(path: Path) -> Path:
    output = path.expanduser().resolve()
    if output in {ROOT, SOURCE} or SOURCE in output.parents:
        raise ValueError("output must not replace the repository or source plugin tree")
    if output.exists() and not (output / MARKER).is_file():
        raise ValueError(f"refusing to replace unmarked output directory: {output}")
    return output


def strip_mcp_registration(plugin_root: Path) -> None:
    for relative_path in (".mcp.json", "mcp.json"):
        candidate = plugin_root / relative_path
        if candidate.exists() or candidate.is_symlink():
            candidate.unlink()

    gemini_path = plugin_root / "gemini-extension.json"
    manifest = json.loads(gemini_path.read_text(encoding="utf-8"))
    manifest.pop("mcpServers", None)
    gemini_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


def build(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}-", dir=output.parent))
    try:
        shutil.rmtree(staging)
        shutil.copytree(SOURCE, staging, symlinks=True)
        strip_mcp_registration(staging)
        (staging / MARKER).write_text(
            "Generated by scripts/build-no-mcp-marketplace.py; do not edit.\n",
            encoding="utf-8",
        )
        if output.exists():
            shutil.rmtree(output)
        os.replace(staging, output)
    finally:
        if staging.exists():
            shutil.rmtree(staging)


def main() -> int:
    try:
        output = resolve_output(parse_args().output)
        build(output)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"built no-MCP marketplace artifact: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
